version: '3.7'

x-env: &env
    env_file:
      - reflask-env.txt
      - reflask-private.txt

services:

  proxy-ssl:
    image: ${REGISTRY}/reflask/proxy-ssl:${TAG_NO}
    build:
      context: ..
      dockerfile: ./containers/proxy-ssl/Dockerfile

  portainer:
    image: ${REGISTRY}/reflask/portainer:${TAG_NO}
    build:
      context: ..
      dockerfile: ./containers/portainer/Dockerfile

  redis:
    image: ${REGISTRY}/reflask/redis:${TAG_NO}
    build:
      context: ..
      dockerfile: ./containers/redis/Dockerfile

  flower:
    image: ${REGISTRY}/reflask/flower:${TAG_NO}
    build:
      context: ..
      dockerfile: ./containers/flower/Dockerfile

  postgres:
    image: ${REGISTRY}/reflask/postgres:${TAG_NO}
    build:
      args:
        REGISTRY: ${REGISTRY}
        TAG_NO: ${TAG_NO}
      context: ..
      dockerfile: ./containers/postgres/Dockerfile

  flask:
    image: ${REGISTRY}/reflask/flask:${TAG_NO}
    build:
      args:
        REGISTRY: ${REGISTRY}
        TAG_NO: ${TAG_NO}
      context: ..
      dockerfile: ./containers/flask/Dockerfile

  api:
    image: ${REGISTRY}/reflask/api:${TAG_NO}
    build:
      args:
        REGISTRY: ${REGISTRY}
        TAG_NO: ${TAG_NO}
      context: ..
      dockerfile: ./containers/api/Dockerfile

  web:
    image: ${REGISTRY}/reflask/web:${TAG_NO}
    build:
      args:
        REGISTRY: ${REGISTRY}
        TAG_NO: ${TAG_NO}
      context: ..
      dockerfile: ./containers/web/Dockerfile

  worker:
    image: ${REGISTRY}/reflask/worker:${TAG_NO}
    build:
      args:
        REGISTRY: ${REGISTRY}
        TAG_NO: ${TAG_NO}
      context: ..
      dockerfile: ./containers/worker/Dockerfile

  beater:
    image: ${REGISTRY}/reflask/beater:${TAG_NO}
    build:
      args:
        REGISTRY: ${REGISTRY}
        TAG_NO: ${TAG_NO}
      context: ..
      dockerfile: ./containers/beater/Dockerfile

  admin:
    image: ${REGISTRY}/reflask/admin:${TAG_NO}
    build:
      args:
        REGISTRY: ${REGISTRY}
        TAG_NO: ${TAG_NO}
      context: ..
      dockerfile: ./containers/admin/Dockerfile

  react:
    image: ${REGISTRY}/reflask/react:${TAG_NO}
    build:
      args:
        REGISTRY: ${REGISTRY}
        TAG_NO: ${TAG_NO}
      context: ..
      dockerfile: ./containers/react/Dockerfile
