version: '3.7'

x-env: &env
    env_file:
      - reflask-env.txt
      - reflask-private.txt

services:

  proxy-ssl:
    image: ${REGISTRY}/reflask/proxy-ssl:${TAG_NO}
    hostname: proxy-ssl
    container_name: proxy-ssl
    networks:
      - reflask
    ports:
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  portainer:
    image: ${REGISTRY}/reflask/portainer:${TAG_NO}
    hostname: portainer
    container_name: portainer
    environment:
      - VIRTUAL_HOST=portainer.local.projectscapa.com
      - VIRTUAL_PORT=9000
    networks:
      - reflask
    ports:
      - 9000:9000
      - 9001:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/shm:/dev/shm
      - portainer_data:/data

  redis:
    image: ${REGISTRY}/reflask/redis:${TAG_NO}
    hostname: redis
    container_name: redis
    networks:
      - reflask

  flower:
    image: ${REGISTRY}/reflask/flower:${TAG_NO}
    hostname: flower
    container_name: flower
    environment:
      - VIRTUAL_HOST=flower.local.projectscapa.com
      - VIRTUAL_PORT=5555
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - reflask

  postgres:
    image: ${REGISTRY}/reflask/postgres:${TAG_NO}
    container_name: postgres
    networks:
      - reflask
    volumes:
      - reflask_data:/var/lib/postgresql/data
    <<: *env
    ports:
      - 5432:5432

  api:
    image: ${REGISTRY}/reflask/api:${TAG_NO}
    hostname: api
    container_name: api
    <<: *env
    environment:
      - VIRTUAL_HOST=api.local.projectscapa.com
      - VIRTUAL_PORT=${API_PORT}
      - TAG_NO=${TAG_NO}
    networks:
      - reflask
    volumes:
      - ${REFLASK_SRC}:/service/reflask
    ports:
      - ${API_PORT}:${API_PORT}

  flask:
    image: ${REGISTRY}/reflask/web:${TAG_NO}
    hostname: flask
    container_name: flask
    <<: *env
    environment:
      - VIRTUAL_HOST=flask.local.projectscapa.com
      - VIRTUAL_PORT=${BACK_END_PORT}
      - VIRTUAL_PROTO=https
      - TAG_NO=${TAG_NO}
    networks:
      - reflask
    volumes:
      - ${REFLASK_SRC}:/service/reflask
    ports:
      - ${BACK_END_PORT}:${BACK_END_PORT}

  worker:
    image: ${REGISTRY}/reflask/worker:${TAG_NO}
    hostname: worker
    container_name: worker
    <<: *env
    environment:
      - TAG_NO=${TAG_NO}
    networks:
      - reflask
    volumes:
      - ${REFLASK_SRC}:/service/reflask

  beater:
    image: ${REGISTRY}/reflask/beater:${TAG_NO}
    hostname: beater
    container_name: beater
    <<: *env
    environment:
      - TAG_NO=${TAG_NO}
    networks:
      - reflask
    volumes:
      - ${REFLASK_SRC}:/service/reflask

  admin:
    image: ${REGISTRY}/reflask/admin:${TAG_NO}
    hostname: admin
    container_name: admin
    <<: *env
    environment:
      - VIRTUAL_HOST=admin.local.projectscapa.com
      - VIRTUAL_PORT=${ADMIN_PORT}
      - TAG_NO=${TAG_NO}
    networks:
      - reflask
    volumes:
      - ${REFLASK_SRC}:/service/reflask
    ports:
      - ${ADMIN_PORT}:${ADMIN_PORT}

  react:
    image: ${REGISTRY}/reflask/react:${TAG_NO}
    hostname: react
    container_name: react
    <<: *env
    environment:
      - VIRTUAL_HOST=react.local.projectscapa.com
      - VIRTUAL_PORT=${FRONT_END_PORT}
      - TAG_NO=${TAG_NO}
    networks:
      - reflask
    volumes:
      - ${REFLASK_SRC}:/service/reflask
    ports:
      - ${FRONT_END_PORT}:3000

volumes:
  reflask_data:
    external: true
  portainer_data:
    external: true

networks:
  reflask:
    external: true
